---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:9.6.2
        ports:
        - containerPort: 5432
        env:
        - name: TZ
          value: "Europe/Zurich"
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.postgresqlUsername}}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.postgresqlDatabase}}
        - name: POSTGRESQL_PASSWORD
          value: {{ .Values.postgresql.postgresqlPassword}}
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}
