---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cvmfs-fcc-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1G
  storageClassName: csi-cvmfs-fcc
