# Default values for reana-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

url: reana.ndslabs.org
debug: false
deployment: local
use_cephfs: true

nfs-server-provisioner:
  persistence:
    size: 10Gi

postgresql:
  postgresqlUsername: reana
  postgresqlDatabase: reana
  postgresqlPassword: reana
  db_persistence_path: "/reanadb"


storage:
  persisitent: true
  classname: nfs
  size: 5Gi
  root_path: /tmp/reana
  deploy_nfs: true

shared_volume_path: /var/reana

server:
  image: reanahub/reana-server
  tag: 0.5.0
  pullPolicy: IfNotPresent
  mountpoints:
  env:
    - key: REANA_USER
      value: bengal

message_broker:
  image: reanahub/reana-message-broker
  tag: 0.5.0
  pullPolicy: IfNotPresent

workflow_controller:
  image: reanahub/reana-workflow-controller
  tag: latest
  pullPolicy: IfNotPresent



resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
