---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manila-cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName:  {{ .Values.storage.classname }}
  mountOptions:
    - nonempty
